// OpenNext's generated worker only exports a fetch handler; a scheduled() handler has
// to be layered on top via a custom entrypoint (see
// https://opennext.js.org/cloudflare/howtos/custom-worker). wrangler.jsonc's `main`
// points here instead of straight at .open-next/worker.js.
// @ts-expect-error `.open-next/worker.js` doesn't exist yet at type-check time — it's
// generated by this same `opennextjs-cloudflare build` run, right after the `next
// build` step (that runs this check) completes.
import { default as handler } from "./.open-next/worker.js";
import { createAdminClient } from "./src/lib/supabase/admin";
import { syncFihResults } from "./src/lib/results/sync";

// A few days of buffer around the tournament (2026-08-15 to 2026-08-30) so the cron
// does nothing — no FIH fetch, no DB hit — for the months either side it'll otherwise
// sit deployed and firing for.
const SYNC_WINDOW_START = Date.parse("2026-08-14T00:00:00Z");
const SYNC_WINDOW_END = Date.parse("2026-08-31T00:00:00Z");

export default {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: CloudflareEnv) {
    if (controller.scheduledTime < SYNC_WINDOW_START || controller.scheduledTime > SYNC_WINDOW_END) return;

    // scheduled() runs outside Next's per-request handling, which is what normally
    // seeds process.env from Cloudflare's env bindings — so that has to happen here
    // explicitly before any app code (createAdminClient) reads process.env.
    process.env.SUPABASE_SERVICE_ROLE_KEY = env.SUPABASE_SERVICE_ROLE_KEY;

    const outcome = await syncFihResults(createAdminClient());
    console.log(
      `[fih-sync] applied=${outcome.applied.length} skipped=${outcome.skipped.length}`,
      JSON.stringify(outcome),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
